pipeline {
  agent any
  stages {
    stage("build") {
      steps {
        echo "Building the project..."
      }
    }

    stage("test") {
      steps {
        echo "Testing the project...123"
      }
    }

    stage("deploy") {
      steps {
        echo "Deploying the project..."
      }
    }
  }
}

