pipeline {
    agent {
        label 'master-node'
    }
    stages {
        stage('CreateNodeImage') {
            agent {
                label 'ubuntu-slave'
            }
            steps {
                echo "Bulding docker image"
                sh '''
                original_pwd=$(pwd -P)
                cd docker/docker-examples
                docker image rm -f $(docker images | awk -F ' ' '{print $3}' | tail -n +2) &> /dev/null
                docker build -t localnodeimg:$BUILD_NUMBER .
                cd $original_pwd
                sh '''
            }
        }

        stage('Deploy in QA instance') {
            agent {
                label 'ubuntu-slave'
            }
            steps {
                echo "We are deploying the app"
                sh '''
                docker container stop nodelocalinstance || true
                docker container rm nodelocalinstance  || true
                docker container run -itd --name nodelocalinstance -p 8083:3000 localnodeimg:$BUILD_NUMBER
                sh '''
            }
        }

        stage('Deploy in Stagging instance') {
            agent {
                label 'ubuntu-slave'
            }
            steps {
                timeout(time:5, unit:'MINUTES') {
                    input message: 'Approve the stagging deployment'
                }
                echo "We are deploying the app in stagging env"
                sh '''
                docker container stop nodestaginginstance || true
                docker container rm nodestaginginstance || true
                docker container run -itd --name nodestaginginstance -p 8082:3000 localnodeimg:$BUILD_NUMBER
                sh '''
            }
        }
    }
    post {
        always {
            mail to: 'dtk1418@gmail.com',
            subject: "Job '${JOB_NAME}' (${BUILD_NUMBER}) is waiting for input",
            body: "Please go to ${BUILD_URL} and verify the build"
        }
        success {
            mail bcc: '', body: """Hi Team,
    
            Build #$BUILD_NUMBER is successful, please go through the url
    
            $BUILD_URL
    
            and verify the details.
    
            Regards,
            DevOps Team""", cc: '', from: '', replyTo: '', subject: 'BUILD SUCCESS NOTIFICATION', to: 'dtk1418@gmail.com'
        }
        failure {
            mail bcc: '', body: """Hi Team,
    
            Build #$BUILD_NUMBER is unsuccessful, please go through the url
    
            $BUILD_URL
    
            and verify the details.
    
            Regards,
            DevOps Team""", cc: '', from: '', replyTo: '', subject: 'BUILD FAILED NOTIFICATION', to: 'dtk1418@gmail.com'
        }
    }
}
